name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: docker://earnestresearch/k8s-volume-discovery-dependencies:latest
      with:
        entrypoint: stack 
        args: build --fast --system-ghc
        github_workspace: /home/stackage/github
    - name: Test
      uses: docker://earnestresearch/k8s-volume-discovery-dependencies:latest
      with:
        entrypoint: stack 
        args: test --fast --system-ghc
        github_workspace: /home/stackage/github
