name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: docker://earnestresearch/k8s-volume-discovery-dependencies:latest
      with:
        entrypoint: stack
        args: build --fast --system-ghc --stack-root /root/.stack --allow-different-user
    - name: Test
      uses: docker://earnestresearch/k8s-volume-discovery-dependencies:latest
      with:
        entrypoint: stack 
        args: test --fast --system-ghc --stack-root /root/.stack --allow-different-user
